### ISSUE TITLE
Method to set the transport handler instead of add_handler or add_program(s)

### ISSUE THREAD

**Issue by gabriel** [maxtaco/node-framed-msgpack-rpc#8]
Currently you can add a handler, or program(s):

```
transport.add_program('program.1.test', {
  'someMethod': function(arg, res) {
    ...    
    }}
);
```

It would be nice to be able to set the handler:

```
transport.set_handler(function(method, arg, res) {
  // method could be "program.1.test.someMethod"
});
```

Also it's a little easier to deal with when testing, cause I think (?) the transport responds with null if a handler isn't found and in the go msgpack-rpc library this leads to an error (cause it's expecting a {} or []). (I could be wrong about this part though.)

**Comment by maxtaco** [comment]
I think you're right.  Can we add an error unwrapper like we have in Go?  That might do the trick too.

**Comment by gabriel** [comment]
Maybe instead of returning null if a handler isn't found it should call `response.error({code: XXX, desc: "Method not found: keybase.1.foo.ba"})`. (I do this in the objc msgpack client.)

The error object is something the msgpack-rpc spec doesn't elaborate on but I think it's better than null.

What do you think about adding `set_handler`? I need it for Electron app cause I pass the UI calls from the main process to the renderer process:
https://github.com/keybase/client/blob/master/electron/browser/client.ts#L72

So currently I have to do:
```
transport.add_program('keybase.1.locksmithUi', {
  'promptDeviceName': function(transportArg, transportResponse) {
    ...
  }}
);
```

for every method call to forward it versus a single method:
```
transport.set_handler(function(method, transportArg, transportResponse) {
  ...
});
```

also I can correctly return an error object that the msgpack server expects (code/desc).

**Comment by maxtaco** [comment]
Does it work to make a subclass of transport to get this behavior? Then you
can specify what the 'this' object is.

**Comment by gabriel** [comment]
So the hook_wrapper and "handler pair" don't leave a way to pass through the original method name even if I override.

I made a tiny patch locally so I can set the handler. It's backwards compatible.

```diff
diff --git a/src/dispatch.iced b/src/dispatch.iced
index 199cf5b..c98e4a5 100644
--- a/src/dispatch.iced
+++ b/src/dispatch.iced
@@ -33,6 +33,7 @@ exports.Dispatch = class Dispatch extends Packetizer
     @_handlers = {}
     @_seqid = 1
     @_dbgr = null
+    @_handler = null
     super
 
   ##-----------------------------------------
@@ -170,7 +171,9 @@ exports.Dispatch = class Dispatch extends Packetizer
       response.debug_msg = debug_msg if response
       debug_msg.call()
 
-    if pair? and (hw = @get_hook_wrapper())?
+    if @_handler
+      @_handler(method, param, response)
+    else if pair? and (hw = @get_hook_wrapper())?
       hw { method : pair[1], thisobj : pair[0], param, response, dispatch : @ }
     else if pair then pair[1].call pair[0], param, response, @
     else if response?
@@ -184,6 +187,9 @@ exports.Dispatch = class Dispatch extends Packetizer
   get_handler_this : (m) -> @
   get_hook_wrapper : () -> null
 
+  set_handler : (h) ->
+    @_handler = h
+
   wrap_outgoing_error   : (s) -> s.toString()
   unwrap_incoming_error : (s) -> new Error(s) if typeof(s) is 'string'
```

**Comment by gabriel** [comment]
I anticipate others would find a method like this useful as well without having to think about programs or hooks or whatever.

**Comment by maxtaco** [comment]
Ok! Will patch tonight.

**Comment by maxtaco** [comment]
live v1.1.9, it's called `set_generic_handler` and is called with a
dictionary of named parameters...

**Comment by gabriel** [comment]
works thanks!
